### ISSUE TITLE
Adding more features for books, etc.

### ISSUE THREAD

**Issue by ItzBlueBerries** [ItzBlueBerries/Publisher#1]
```yaml
BOOK TO-DO LIST:
   - Favorite Books
   - Top Favorited Books
   - Read Count (Maybe)
PUBLISH TO-DO LIST:
   - Book removal support.
   - Reset all books support.
   - Anything else that publishers should have access to.
```
